# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
streams = Stream.create([{streamCode:"STRU-CMPSC", streamName:"Computer Science"},
                        {streamCode:"STRU-SWENG", streamName:"Software Engineering"},
                        {streamCode:"STRU-CYBSC", streamName:"Cyber Security"},
                        {streamCode:"STRU-INFTC", streamName:"Information Technology"}])

units = Unit.create([{unitCode:"ELEC0000", unitName:"Elective", creditPoints:"25", semAvailable:"0", preUnit: "false"},
                    {unitCode:"COMP1001", unitName:"Object Oriented Program Design", creditPoints:"25", semAvailable:"0", preUnit: "false"},
                    {unitCode:"ISAD1000", unitName:"Introduction to Software Engineering", creditPoints:"25", semAvailable:"1", preUnit: "false"},
                    {unitCode:"MATH1004", unitName:"Mathematics 1", creditPoints:"25", semAvailable:"0", preUnit: "false"},
                    {unitCode:"STAT1002", unitName:"Statistical Data Analysis", creditPoints:"12.5", semAvailable:"1", preUnit: "false"},
                    {unitCode:"COMS1000", unitName:"Science Communications", creditPoints:"12.5", semAvailable:"0", preUnit: "false"},
                    {unitCode:"COMP1002", unitName:"Data Structure and Algorithms", creditPoints:"25", semAvailable:"0", preUnit: "true"},
                    {unitCode:"COMP1000", unitName:"Unix & C Programming", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"ISYS1001", unitName:"Database Systems", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"CNCO2000", unitName:"Computer Communication", creditPoints:"25", semAvailable:"1", preUnit: "true"},
                    {unitCode:"COMP2006", unitName:"Operating Systems", creditPoints:"25", semAvailable:"1", preUnit: "true"},
                    {unitCode:"MATH1011", unitName:"Mathematics 2", creditPoints:"25", semAvailable:"0", preUnit: "true"},
                    {unitCode:"COMP2003", unitName:"Object Oriented Software Engineering", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"COMP2004", unitName:"Computer Graphics", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"COMP2001", unitName:"Foundations of Computer Science", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"COMP2007", unitName:"Programming Languages", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"ISAD3000", unitName:"Software Engineering Project 1", creditPoints:"25", semAvailable:"1", preUnit: "true"},
                    {unitCode:"COMP3006", unitName:"Artificial & Machine Intelligence", creditPoints:"25", semAvailable:"1", preUnit: "true"},
                    {unitCode:"COMP3001", unitName:"Design & Analysis of Algorithms", creditPoints:"25", semAvailable:"1", preUnit: "true"},
                    {unitCode:"PRJM3000", unitName:"Project Design & Management", creditPoints:"25", semAvailable:"1", preUnit: "true"},
                    {unitCode:"ISAD3001", unitName:"Software Engineering Project 2", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"ICTE4000", unitName:"Human Computer Interface", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"COMP4001", unitName:"Machine Perception", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"COMP3002", unitName:"Theoretical Foundations of Computer Science", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"CMPE2002", unitName:"Requirements Engineering", creditPoints:"25", semAvailable:"2", preUnit: "false"},
                    {unitCode:"ISAD4002", unitName:"Software Metrics", creditPoints:"25", semAvailable:"1", preUnit: "true"},
                    {unitCode:"ISEC2000", unitName:"Fundamental Concepts of Cryptography", creditPoints:"25", semAvailable:"1", preUnit: "true"},
                    {unitCode:"COMP3003", unitName:"Software Engineering Concepts", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"CMPE4001", unitName:"Software Engineering Testing", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"ISEC2001", unitName:"Fundamental Concepts of Cyber Security", creditPoints:"25", semAvailable:"1", preUnit: "true"},
                    {unitCode:"ISEC3001", unitName:"Advanced Cryptography", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"ISEC3002", unitName:"Network Security & Firewalls", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"ISEC3003", unitName:"Cyber Security Concepts", creditPoints:"25", semAvailable:"1", preUnit: "true"},
                    {unitCode:"ISEC3005", unitName:"Cyber Security: Intrusion Detection System & Incident Handling", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"ISEC3004", unitName:"Cyber Crime & Security Enhanced Programming", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"CMPE1000", unitName:"Hardware Fundamentals", creditPoints:"25", semAvailable:"1", preUnit: "false"},
                    {unitCode:"CNCO3002", unitName:"Advanced Computer Communications", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"COMP2002", unitName:"Unix Systems Programming", creditPoints:"25", semAvailable:"2", preUnit: "true"},
                    {unitCode:"COMP4002", unitName:"Software Components", creditPoints:"25", semAvailable:"1", preUnit: "true"},
                    {unitCode:"CNCO3001", unitName:"Network Systems Design", creditPoints:"25", semAvailable:"2", preUnit: "true"}])

streamunit = StreamUnit.create([{stream_id:"1", unit_id:"2", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"1", unit_id:"3", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"1", unit_id:"4", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"1", unit_id:"5", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"1", unit_id:"6", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"1", unit_id:"7", plannedYear:"1", plannedSemester:"2"},
                               {stream_id:"1", unit_id:"8", plannedYear:"1", plannedSemester:"2"},
                               {stream_id:"1", unit_id:"9", plannedYear:"1", plannedSemester:"2"},
                               {stream_id:"1", unit_id:"1", plannedYear:"1", plannedSemester:"2"},
                               {stream_id:"1", unit_id:"10", plannedYear:"2", plannedSemester:"1"},
                               {stream_id:"1", unit_id:"11", plannedYear:"2", plannedSemester:"1"},
                               {stream_id:"1", unit_id:"12", plannedYear:"2", plannedSemester:"1"},
                               {stream_id:"1", unit_id:"1", plannedYear:"2", plannedSemester:"1"},
                               {stream_id:"1", unit_id:"13", plannedYear:"2", plannedSemester:"2"},
                               {stream_id:"1", unit_id:"14", plannedYear:"2", plannedSemester:"2"},
                               {stream_id:"1", unit_id:"15", plannedYear:"2", plannedSemester:"2"},
                               {stream_id:"1", unit_id:"16", plannedYear:"2", plannedSemester:"2"},
                               {stream_id:"1", unit_id:"17", plannedYear:"3", plannedSemester:"1"},
                               {stream_id:"1", unit_id:"18", plannedYear:"3", plannedSemester:"1"},
                               {stream_id:"1", unit_id:"19", plannedYear:"3", plannedSemester:"1"},
                               {stream_id:"1", unit_id:"20", plannedYear:"3", plannedSemester:"1"},
                               {stream_id:"1", unit_id:"21", plannedYear:"3", plannedSemester:"2"},
                               {stream_id:"1", unit_id:"22", plannedYear:"3", plannedSemester:"2"},
                               {stream_id:"1", unit_id:"23", plannedYear:"3", plannedSemester:"2"},
                               {stream_id:"1", unit_id:"24", plannedYear:"3", plannedSemester:"2"},
                               {stream_id:"2", unit_id:"2", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"2", unit_id:"3", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"2", unit_id:"4", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"2", unit_id:"5", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"2", unit_id:"6", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"2", unit_id:"7", plannedYear:"1", plannedSemester:"2"},
                               {stream_id:"2", unit_id:"8", plannedYear:"1", plannedSemester:"2"},
                               {stream_id:"2", unit_id:"9", plannedYear:"1", plannedSemester:"2"},
                               {stream_id:"2", unit_id:"1", plannedYear:"1", plannedSemester:"2"},
                               {stream_id:"2", unit_id:"10", plannedYear:"2", plannedSemester:"1"},
                               {stream_id:"2", unit_id:"11", plannedYear:"2", plannedSemester:"1"},
                               {stream_id:"2", unit_id:"20", plannedYear:"2", plannedSemester:"1"},
                               {stream_id:"2", unit_id:"1", plannedYear:"2", plannedSemester:"1"},
                               {stream_id:"2", unit_id:"13", plannedYear:"2", plannedSemester:"2"},
                               {stream_id:"2", unit_id:"14", plannedYear:"2", plannedSemester:"2"},
                               {stream_id:"2", unit_id:"25", plannedYear:"2", plannedSemester:"2"},
                               {stream_id:"2", unit_id:"1", plannedYear:"2", plannedSemester:"2"},
                               {stream_id:"2", unit_id:"17", plannedYear:"3", plannedSemester:"1"},
                               {stream_id:"2", unit_id:"26", plannedYear:"3", plannedSemester:"1"},
                               {stream_id:"2", unit_id:"19", plannedYear:"3", plannedSemester:"1"},
                               {stream_id:"2", unit_id:"27", plannedYear:"3", plannedSemester:"1"},
                               {stream_id:"2", unit_id:"21", plannedYear:"3", plannedSemester:"2"},
                               {stream_id:"2", unit_id:"22", plannedYear:"3", plannedSemester:"2"},
                               {stream_id:"2", unit_id:"28", plannedYear:"3", plannedSemester:"2"},
                               {stream_id:"2", unit_id:"29", plannedYear:"3", plannedSemester:"2"},
                               {stream_id:"3", unit_id:"2", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"3", unit_id:"3", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"3", unit_id:"4", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"3", unit_id:"5", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"3", unit_id:"6", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"3", unit_id:"7", plannedYear:"1", plannedSemester:"2"},
                               {stream_id:"3", unit_id:"8", plannedYear:"1", plannedSemester:"2"},
                               {stream_id:"3", unit_id:"9", plannedYear:"1", plannedSemester:"2"},
                               {stream_id:"3", unit_id:"1", plannedYear:"1", plannedSemester:"2"},
                               {stream_id:"3", unit_id:"10", plannedYear:"2", plannedSemester:"1"},
                               {stream_id:"3", unit_id:"11", plannedYear:"2", plannedSemester:"1"},
                               {stream_id:"3", unit_id:"27", plannedYear:"2", plannedSemester:"1"},
                               {stream_id:"3", unit_id:"30", plannedYear:"2", plannedSemester:"1"},
                               {stream_id:"3", unit_id:"13", plannedYear:"2", plannedSemester:"2"},
                               {stream_id:"3", unit_id:"31", plannedYear:"2", plannedSemester:"2"},
                               {stream_id:"3", unit_id:"32", plannedYear:"2", plannedSemester:"2"},
                               {stream_id:"3", unit_id:"1", plannedYear:"2", plannedSemester:"2"},
                               {stream_id:"3", unit_id:"17", plannedYear:"3", plannedSemester:"1"},
                               {stream_id:"3", unit_id:"33", plannedYear:"3", plannedSemester:"1"},
                               {stream_id:"3", unit_id:"19", plannedYear:"3", plannedSemester:"1"},
                               {stream_id:"3", unit_id:"20", plannedYear:"3", plannedSemester:"1"},
                               {stream_id:"3", unit_id:"21", plannedYear:"3", plannedSemester:"2"},
                               {stream_id:"3", unit_id:"22", plannedYear:"3", plannedSemester:"2"},
                               {stream_id:"3", unit_id:"34", plannedYear:"3", plannedSemester:"2"},
                               {stream_id:"3", unit_id:"35", plannedYear:"3", plannedSemester:"2"},
                               {stream_id:"4", unit_id:"2", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"4", unit_id:"3", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"4", unit_id:"4", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"4", unit_id:"5", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"4", unit_id:"6", plannedYear:"1", plannedSemester:"1"},
                               {stream_id:"4", unit_id:"7", plannedYear:"1", plannedSemester:"2"},
                               {stream_id:"4", unit_id:"8", plannedYear:"1", plannedSemester:"2"},
                               {stream_id:"4", unit_id:"9", plannedYear:"1", plannedSemester:"2"},
                               {stream_id:"4", unit_id:"1", plannedYear:"1", plannedSemester:"2"},
                               {stream_id:"4", unit_id:"10", plannedYear:"2", plannedSemester:"1"},
                               {stream_id:"4", unit_id:"36", plannedYear:"2", plannedSemester:"1"},
                               {stream_id:"4", unit_id:"27", plannedYear:"2", plannedSemester:"1"},
                               {stream_id:"4", unit_id:"1", plannedYear:"2", plannedSemester:"1"},
                               {stream_id:"4", unit_id:"13", plannedYear:"2", plannedSemester:"2"},
                               {stream_id:"4", unit_id:"14", plannedYear:"2", plannedSemester:"2"},
                               {stream_id:"4", unit_id:"37", plannedYear:"2", plannedSemester:"2"},
                               {stream_id:"4", unit_id:"38", plannedYear:"2", plannedSemester:"2"},
                               {stream_id:"4", unit_id:"17", plannedYear:"3", plannedSemester:"1"},
                               {stream_id:"4", unit_id:"11", plannedYear:"3", plannedSemester:"1"},
                               {stream_id:"4", unit_id:"39", plannedYear:"3", plannedSemester:"1"},
                               {stream_id:"4", unit_id:"20", plannedYear:"3", plannedSemester:"1"},
                               {stream_id:"4", unit_id:"21", plannedYear:"3", plannedSemester:"2"},
                               {stream_id:"4", unit_id:"22", plannedYear:"3", plannedSemester:"2"},
                               {stream_id:"4", unit_id:"40", plannedYear:"3", plannedSemester:"2"},
                               {stream_id:"4", unit_id:"1", plannedYear:"3", plannedSemester:"2"}])


prereqgroup = PreReqGroup.create([{unit_id:"7"},
                                  {unit_id:"8"},
                                  {unit_id:"8"},
                                  {unit_id:"9"},
                                  {unit_id:"10"},
                                  {unit_id:"11"},
                                  {unit_id:"12"},
                                  {unit_id:"13"},
                                  {unit_id:"14"},
                                  {unit_id:"14"},
                                  {unit_id:"15"},
                                  {unit_id:"16"},
                                  {unit_id:"17"},
                                  {unit_id:"18"},
                                  {unit_id:"19"},
                                  {unit_id:"20"},
                                  {unit_id:"21"},
                                  {unit_id:"22"},
                                  {unit_id:"23"},
                                  {unit_id:"24"},
                                  {unit_id:"26"},
                                  {unit_id:"27"},
                                  {unit_id:"28"},
                                  {unit_id:"29"},
                                  {unit_id:"30"},
                                  {unit_id:"31"},
                                  {unit_id:"32"},
                                  {unit_id:"33"},
                                  {unit_id:"35"},
                                  {unit_id:"37"},
                                  {unit_id:"38"},
                                  {unit_id:"39"},
                                  {unit_id:"40"},])

prereq = PreReq.create([{pre_req_group_id:"1", unit_id:"7", preUnit_code:"COMP1001"},
                        {pre_req_group_id:"2", unit_id:"8", preUnit_code:"COMP1001"},
                        {pre_req_group_id:"3", unit_id:"8", preUnit_code:"COMP1004"},
                        {pre_req_group_id:"4", unit_id:"9", preUnit_code:"COMP1001"},
                        {pre_req_group_id:"5", unit_id:"10", preUnit_code:"COMP1001"},
                        {pre_req_group_id:"5", unit_id:"10", preUnit_code:"COMP2002"},
                        {pre_req_group_id:"6", unit_id:"11", preUnit_code:"COMP1000"},
                        {pre_req_group_id:"6", unit_id:"11", preUnit_code:"COMP1002"},
                        {pre_req_group_id:"7", unit_id:"12", preUnit_code:"COMP1004"},
                        {pre_req_group_id:"8", unit_id:"13", preUnit_code:"COMP1002"},
                        {pre_req_group_id:"9", unit_id:"14", preUnit_code:"COMP1000"},
                        {pre_req_group_id:"9", unit_id:"14", preUnit_code:"COMP1002"},
                        {pre_req_group_id:"10", unit_id:"14", preUnit_code:"COMP1002"},
                        {pre_req_group_id:"10", unit_id:"14", preUnit_code:"COMP2004"},
                        {pre_req_group_id:"11", unit_id:"15", preUnit_code:"COMP1001"},
                        {pre_req_group_id:"12", unit_id:"16", preUnit_code:"COMP1000"},
                        {pre_req_group_id:"12", unit_id:"16", preUnit_code:"COMP1002"},
                        {pre_req_group_id:"13", unit_id:"17", preUnit_code:"COMP2003"},
                        {pre_req_group_id:"14", unit_id:"18", preUnit_code:"COMP1000"},
                        {pre_req_group_id:"14", unit_id:"18", preUnit_code:"COMP1004"},
                        {pre_req_group_id:"15", unit_id:"19", preUnit_code:"COMP1002"},
                        {pre_req_group_id:"16", unit_id:"20", preUnit_code:"ISAD1000"},
                        {pre_req_group_id:"16", unit_id:"20", preUnit_code:"ISYS1001"},
                        {pre_req_group_id:"17", unit_id:"21", preUnit_code:"COMP2003"},
                        {pre_req_group_id:"18", unit_id:"22", preUnit_code:"COMP1002"},
                        {pre_req_group_id:"18", unit_id:"22", preUnit_code:"ISAD1000"},
                        {pre_req_group_id:"19", unit_id:"23", preUnit_code:"COMP1000"},
                        {pre_req_group_id:"19", unit_id:"23", preUnit_code:"COMP1002"},
                        {pre_req_group_id:"20", unit_id:"24", preUnit_code:"COMP1001"},
                        {pre_req_group_id:"20", unit_id:"24", preUnit_code:"COMP1002"},
                        {pre_req_group_id:"21", unit_id:"26", preUnit_code:"COMP2003"},
                        {pre_req_group_id:"22", unit_id:"27", preUnit_code:"MATH1004"},
                        {pre_req_group_id:"22", unit_id:"27", preUnit_code:"STAT1002"},
                        {pre_req_group_id:"22", unit_id:"27", preUnit_code:"COMP1002"},
                        {pre_req_group_id:"23", unit_id:"28", preUnit_code:"COMP2003"},
                        {pre_req_group_id:"24", unit_id:"29", preUnit_code:"ISAD1000"},
                        {pre_req_group_id:"25", unit_id:"30", preUnit_code:"COMS1000"},
                        {pre_req_group_id:"25", unit_id:"30", preUnit_code:"ISAD1000"},
                        {pre_req_group_id:"26", unit_id:"31", preUnit_code:"ISEC2000"},
                        {pre_req_group_id:"27", unit_id:"32", preUnit_code:"CNCO2000"},
                        {pre_req_group_id:"28", unit_id:"33", preUnit_code:"COMP1001"},
                        {pre_req_group_id:"28", unit_id:"33", preUnit_code:"COMP1002"},
                        {pre_req_group_id:"29", unit_id:"35", preUnit_code:"COMP2006"},
                        {pre_req_group_id:"29", unit_id:"35", preUnit_code:"ISYS1001"},
                        {pre_req_group_id:"30", unit_id:"37", preUnit_code:"CNCO2000"},
                        {pre_req_group_id:"31", unit_id:"38", preUnit_code:"COMP1000"},
                        {pre_req_group_id:"31", unit_id:"38", preUnit_code:"COMP1002"},
                        {pre_req_group_id:"32", unit_id:"39", preUnit_code:"ISYS1001"},
                        {pre_req_group_id:"32", unit_id:"39", preUnit_code:"COMP2003"},
                        {pre_req_group_id:"33", unit_id:"40", preUnit_code:"CNCO2000"},
                        {pre_req_group_id:"33", unit_id:"40", preUnit_code:"COMP1000"},
                        {pre_req_group_id:"33", unit_id:"40", preUnit_code:"COMP1002"}])

user = User.new
user.email = "admin"
user.password = "admin"
user.password_confirmation = "admin"
user.save!